@startuml

autonumber

actor Student
participant "app:\n InschrijfApp" as app
participant "course:\nCourse" as course
participant "student:\nStudent" as student
database Store

Student -> app: schrijfIn(: \n\
    studentID,\n\
    courseID)

@enduml