@startuml
hide circle

class Vertoning <<entity>> {
  titel
  datum
  tijd
  getBeschikbareStoelen()
  reserveerStoel(stoelId)
}

class Stoel <<entity>> {
  stoelId
  isBeschikbaar
  reserveer()
}

class Kaartje <<Value Object>> {
    Kaartje()
}

Vertoning "1" --> "*" Stoel

@enduml