@startuml

actor Speler

autonumber

participant app as "app:\nAdventureQuestApp"
participant spel as "spel:\nSpel"
participant karakter as "karakter:\nKarakter"
participant doelVakje as "Vakje"
participant huidigVakje as "Vakje"
database Store

Speler --> app: verplaats(\n\
    spelId,\n\
    karakterId)

app -> Store: spel = findSpel(spelId)

spel -> Store: karakter = findKarakter(karakterId)

spel -> karakter: huidigVakje = getHuidigVakje()

spel -> spel: doelVakje = findVakje(doelVakjeId)

spel -> doelVakje: isLeeg = isLeeg()

opt isLeeg = true

    opt genoegEnergie = true
        spel -> huidigVakje: verwijderKarakter()
        spel -> doelVakje: plaatsKarakter(karakter)
        spel -> karakter: setHuidigVakje(doelVakje)
    end
end
@enduml