@startuml

actor Speler

participant app as "app:\nAdventureQuestApp"
participant spel as "spel:\nSpel"
participant karakter as "karakter:\nKarakter"
participant doelVakje as "Vakje"
participant huidigVakje as "Vakje"
database Store

note over doelVakje
Hallo dit is een note
end note

Speler --> app: verplaats(\n\
    spelId,\n\
    karakterId)

app -> Store: spel = find spel(spelId)

spel -> Store: karakter = findKarakter(karakterId)

spel -> karakter: huidigVakje = getHuidigVakje()

note over spel
parameter mogen niet
uit de lucht komen vallen:
doelVakjeId
end note

spel -> spel: doelVakje = findVakje(doelVakjeId)

spel -> doelVakje: isLeeg = isLeeg()

opt isLeeg = true

    opt genoegEnergie = true
        spel -> huidigVakje: verwijderKarakter()
        spel -> doelVakje: plaatsKarakter(karakter)
        spel -> karakter: setHuidigVakje(doelVakje)
    end
end
@enduml