@startuml
hide circle

 skinparam linetype ortho

rectangle "Aggregate Bestelling" {
    class Bestelling <<Aggregate Root>> {
        budget
        berekenTotaal()
        voegToe(product, aantal)
    }

    class BestelRegel <<Entity>> {
        aantal
    }
}

rectangle "Aggregate \n Product" {
    class Product <<Aggregate Root>> {
        prijs
    }
}

Bestelling "1" -r- "*" BestelRegel
BestelRegel "1" -r-> "1" Product

@enduml