@startuml
Title optie 2

participant "app:\nBestelApp" as app
participant "bestelling:\nBestelling" as bestelling
participant "bestelregel:\nBestelRegel" as bestelregel
participant "product:\nProduct" as product
database Store

app -> Store: product = findProduct(productId)
app -> Store: bestelling = findBestelling(bestellingId)
app -> bestelling: voegToe(product, aantal)
bestelling -> bestelregel **: bestelregel = new(product, aantal)
bestelling -> bestelregel: getSubtotaal()
bestelregel -> product: prijs = getPrijs()
bestelling <-- bestelregel: subtotaal

bestelling -> bestelling: addBestelRegel(bestelregel)
@enduml